version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    network_mode: "bridge"
    environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sicaadmin
      MONGO_INITDB_ROOT_PASSWORD: sica
    ports:
      - "27017:27017"
    volumes:
      - D:\\Desenv\\mongo_data_docker:/data/db
  postgres:
    build: ./postgresql
    image: sica/postgresql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - D:\\Desenv\\pg_data_docker:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sica
      - POSTGRES_DB=sica
      - POSTGRES_INITDB_ARGS=--locale=pt_BR.UTF8
      - TZ=America/Sao_Paulo
volumes:
  sicafiles: {}
