version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "5672"
      - "15672:15672"
    networks:
      - sica-network
    environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
  mongo:
    build: ./mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: sica
      MONGO_INITDB_USERNAME: sicaMonitoramento
      MONGO_INITDB_PASSWORD: sica
      MONGO_INITDB_DATABASE: sica
    ports:
      - "27017"
    networks:
      - sica-network
  postgres:
    build: ./postgresql
    restart: always
    ports:
      - "5432"
    networks:
      - sica-network
    #volumes:
      #- postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sica
      - POSTGRES_DB=sica
      - POSTGRES_INITDB_ARGS=--locale=pt_BR.UTF8
      - TZ=America/Sao_Paulo
  sica-ativos:
    build: ../workspace/sica-ativos
    ports:
      - "8091:8080"
    depends_on:
      - postgres
    networks:
      - sica-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sica
  sica-monitoramento:
    build: ../workspace/sica-monitoramento
    ports:
      - "8092:8080"
    depends_on:
      - rabbitmq
      - mongo
      - postgres
    networks:
      - sica-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sica
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_DATA_MONGODB_URI=mongodb://sicaMonitoramento:sica@mongo:27017/sica?authSource=admin&authMechanism=SCRAM-SHA-1
  sica-seguranca:
    build: ../workspace/sica-seguranca
    ports:
      - "8093:8080"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - sica-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sica
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
  sica-portal:
    build: ../workspace/sica-portal-web
    ports:
      - "8090:8080"
    depends_on:
      - sica-ativos
      - sica-monitoramento
      - sica-seguranca
    networks:
      - sica-network
    environment:
      - MODULO_URL_ATIVOS=http://sica-ativos:8080/
      - MODULO_URL_MONITORAMENTO=http://sica-monitoramento:8080/
      - MODULO_URL_SEGURANCA=http://sica-seguranca:8080/
networks:
    sica-network:
        driver: bridge